//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 07:53:57 PM MESZ 
//


package de.odenthma.geocache.UserInformation.Classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for userType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userInformation" type="{}userInformationType"/>
 *         &lt;element name="account" type="{}accountType"/>
 *         &lt;element name="optional" type="{}optionalType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="b_id" use="required" type="{}bIdRestriction" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userType", propOrder = {
    "userInformation",
    "account",
    "optional"
})
public class UserType {

    @XmlElement(required = true)
    protected UserInformationType userInformation;
    @XmlElement(required = true)
    protected AccountType account;
    @XmlElement(required = true)
    protected OptionalType optional;
    @XmlAttribute(name = "b_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bId;

    /**
     * Gets the value of the userInformation property.
     * 
     * @return
     *     possible object is
     *     {@link UserInformationType }
     *     
     */
    public UserInformationType getUserInformation() {
        return userInformation;
    }

    /**
     * Sets the value of the userInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInformationType }
     *     
     */
    public void setUserInformation(UserInformationType value) {
        this.userInformation = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setAccount(AccountType value) {
        this.account = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalType }
     *     
     */
    public OptionalType getOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalType }
     *     
     */
    public void setOptional(OptionalType value) {
        this.optional = value;
    }

    /**
     * Gets the value of the bId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBId() {
        return bId;
    }

    /**
     * Sets the value of the bId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBId(String value) {
        this.bId = value;
    }

}
