//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 05:06:50 PM MESZ 
//


package de.odenthma.geocache.UserInformation.Classes;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for userInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="b_id" use="required" type="{}bIdRestriction" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="accountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anzGefundenerCaches" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="anzErstellterCaches" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cachesGefunden" type="{}cachesGefundenType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cachesErstellt" type="{}cachesErstelltType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="optional" type="{}optionalType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userInformationType", propOrder = {
    "user",
    "accountName",
    "anzGefundenerCaches",
    "anzErstellterCaches",
    "cachesGefunden",
    "cachesErstellt",
    "optional"
})
public class UserInformationType {

    @XmlElement(required = true)
    protected List<User> user;
    @XmlElement(required = true)
    protected String accountName;
    @XmlElement(required = true)
    protected BigDecimal anzGefundenerCaches;
    @XmlElement(required = true)
    protected BigDecimal anzErstellterCaches;
    @XmlElement(required = true)
    protected List<CachesGefundenType> cachesGefunden;
    @XmlElement(required = true)
    protected List<CachesErstelltType> cachesErstellt;
    @XmlElement(required = true)
    protected OptionalType optional;

    /**
     * Gets the value of the user property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the user property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link User }
     * 
     * 
     */
    public List<User> getUser() {
        if (user == null) {
            user = new ArrayList<User>();
        }
        return this.user;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the anzGefundenerCaches property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAnzGefundenerCaches() {
        return anzGefundenerCaches;
    }

    /**
     * Sets the value of the anzGefundenerCaches property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAnzGefundenerCaches(BigDecimal value) {
        this.anzGefundenerCaches = value;
    }

    /**
     * Gets the value of the anzErstellterCaches property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAnzErstellterCaches() {
        return anzErstellterCaches;
    }

    /**
     * Sets the value of the anzErstellterCaches property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAnzErstellterCaches(BigDecimal value) {
        this.anzErstellterCaches = value;
    }

    /**
     * Gets the value of the cachesGefunden property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cachesGefunden property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCachesGefunden().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CachesGefundenType }
     * 
     * 
     */
    public List<CachesGefundenType> getCachesGefunden() {
        if (cachesGefunden == null) {
            cachesGefunden = new ArrayList<CachesGefundenType>();
        }
        return this.cachesGefunden;
    }

    /**
     * Gets the value of the cachesErstellt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cachesErstellt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCachesErstellt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CachesErstelltType }
     * 
     * 
     */
    public List<CachesErstelltType> getCachesErstellt() {
        if (cachesErstellt == null) {
            cachesErstellt = new ArrayList<CachesErstelltType>();
        }
        return this.cachesErstellt;
    }

    /**
     * Gets the value of the optional property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalType }
     *     
     */
    public OptionalType getOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalType }
     *     
     */
    public void setOptional(OptionalType value) {
        this.optional = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="b_id" use="required" type="{}bIdRestriction" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class User {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "b_id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String bId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the bId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBId() {
            return bId;
        }

        /**
         * Sets the value of the bId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBId(String value) {
            this.bId = value;
        }

    }

}
