//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 04:28:08 PM MESZ 
//


package de.odenthma.geocache.CacheClasses;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;




@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CacheListType", propOrder = {
    "cache"
})
@XmlRootElement(name = "CacheList")
public class CacheListType {

    @XmlElement(name = "Cache", required = true)
    protected ArrayList<CacheType> cache;

    public ArrayList<CacheType> getCache() {
        if (cache == null) {
            cache = new ArrayList<CacheType>();
        }
        return this.cache;
    }
}

