//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 01:08:00 AM MESZ 
//


package de.odenthma.geocache.CacheClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import de.odenthma.geocache.CacheClasses.LogType.GefundenVon;


/**
 * <p>Java class for logType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gefundenVon">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="b_id" use="required" type="{}bIdRestriction" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gefundenDatum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="kommentar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logType", propOrder = {
    "gefundenVon",
    "gefundenDatum",
    "kommentar"
})
public class LogType {

    @XmlElement(required = true)
    protected GefundenVon gefundenVon;
    @XmlElement(required = true)
    protected XMLGregorianCalendar gefundenDatum;
    @XmlElement(required = true)
    protected String kommentar;

    /**
     * Gets the value of the gefundenVon property.
     * 
     * @return
     *     possible object is
     *     {@link GefundenVon }
     *     
     */
    public GefundenVon getGefundenVon() {
        return gefundenVon;
    }

    /**
     * Sets the value of the gefundenVon property.
     * 
     * @param value
     *     allowed object is
     *     {@link GefundenVon }
     *     
     */
    public void setGefundenVon(GefundenVon value) {
        this.gefundenVon = value;
    }

    /**
     * Gets the value of the gefundenDatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGefundenDatum() {
        return gefundenDatum;
    }

    /**
     * Sets the value of the gefundenDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGefundenDatum(XMLGregorianCalendar value) {
        this.gefundenDatum = value;
    }

    /**
     * Gets the value of the kommentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKommentar() {
        return kommentar;
    }

    /**
     * Sets the value of the kommentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKommentar(String value) {
        this.kommentar = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="b_id" use="required" type="{}bIdRestriction" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class GefundenVon {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "b_id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String bId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the bId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBId() {
            return bId;
        }

        /**
         * Sets the value of the bId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBId(String value) {
            this.bId = value;
        }

    }

}
