//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 07:53:57 PM MESZ 
//


package de.odenthma.geocache.generatedclasses.userinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for accountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="logInName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logInPW" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{}mailRestriction"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountType", propOrder = {
    "logInName",
    "logInPW",
    "email"
})
public class AccountType {

    @XmlElement(required = true)
    protected String logInName;
    @XmlElement(required = true)
    protected String logInPW;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String email;

    /**
     * Gets the value of the logInName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogInName() {
        return logInName;
    }

    /**
     * Sets the value of the logInName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogInName(String value) {
        this.logInName = value;
    }

    /**
     * Gets the value of the logInPW property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogInPW() {
        return logInPW;
    }

    /**
     * Sets the value of the logInPW property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogInPW(String value) {
        this.logInPW = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

}
