//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 07:53:57 PM MESZ 
//


package de.odenthma.geocache.generatedclasses.userinformation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import de.odenthma.geocache.generatedclasses.userinformation.OptionalType.Benachrichtigung;
import de.odenthma.geocache.generatedclasses.userinformation.OptionalType.News;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserList_QNAME = new QName("", "userList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link OptionalType }
     * 
     */
    public OptionalType createOptionalType() {
        return new OptionalType();
    }

    /**
     * Create an instance of {@link Benachrichtigung }
     * 
     */
    public Benachrichtigung createOptionalTypeBenachrichtigung() {
        return new Benachrichtigung();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link UserListType }
     * 
     */
    public UserListType createUserListType() {
        return new UserListType();
    }

    /**
     * Create an instance of {@link News }
     * 
     */
    public News createOptionalTypeNews() {
        return new News();
    }

    /**
     * Create an instance of {@link OrtsListeType }
     * 
     */
    public OrtsListeType createOrtsListeType() {
        return new OrtsListeType();
    }

    /**
     * Create an instance of {@link OrtsType }
     * 
     */
    public OrtsType createOrtsType() {
        return new OrtsType();
    }

    /**
     * Create an instance of {@link AdressType }
     * 
     */
    public AdressType createAdressType() {
        return new AdressType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link UserInformationType }
     * 
     */
    public UserInformationType createUserInformationType() {
        return new UserInformationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userList")
    public JAXBElement<UserListType> createUserList(UserListType value) {
        return new JAXBElement<UserListType>(_UserList_QNAME, UserListType.class, null, value);
    }

}
