//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 07:53:57 PM MESZ 
//


package de.odenthma.geocache.generatedclasses.userinformation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;



/**
 * <p>Java class for optionalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optionalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="news">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="wanted" use="required" type="{}yesNoEnum" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="benachrichtigung">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="wanted" use="required" type="{}yesNoEnum" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ortsListe" type="{}ortsListeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optionalType", propOrder = {
    "news",
    "benachrichtigung",
    "ortsListe"
})
public class OptionalType {

    @XmlElement(required = true)
    protected News news;
    @XmlElement(required = true)
    protected Benachrichtigung benachrichtigung;
    @XmlElement(required = true)
    protected OrtsListeType ortsListe;

    /**
     * Gets the value of the news property.
     * 
     * @return
     *     possible object is
     *     {@link News }
     *     
     */
    public News getNews() {
        return news;
    }

    /**
     * Sets the value of the news property.
     * 
     * @param value
     *     allowed object is
     *     {@link News }
     *     
     */
    public void setNews(News value) {
        this.news = value;
    }

    /**
     * Gets the value of the benachrichtigung property.
     * 
     * @return
     *     possible object is
     *     {@link Benachrichtigung }
     *     
     */
    public Benachrichtigung getBenachrichtigung() {
        return benachrichtigung;
    }

    /**
     * Sets the value of the benachrichtigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Benachrichtigung }
     *     
     */
    public void setBenachrichtigung(Benachrichtigung value) {
        this.benachrichtigung = value;
    }

    /**
     * Gets the value of the ortsListe property.
     * 
     * @return
     *     possible object is
     *     {@link OrtsListeType }
     *     
     */
    public OrtsListeType getOrtsListe() {
        return ortsListe;
    }

    /**
     * Sets the value of the ortsListe property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrtsListeType }
     *     
     */
    public void setOrtsListe(OrtsListeType value) {
        this.ortsListe = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="wanted" use="required" type="{}yesNoEnum" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Benachrichtigung {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected YesNoEnum wanted;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the wanted property.
         * 
         * @return
         *     possible object is
         *     {@link YesNoEnum }
         *     
         */
        public YesNoEnum getWanted() {
            return wanted;
        }

        /**
         * Sets the value of the wanted property.
         * 
         * @param value
         *     allowed object is
         *     {@link YesNoEnum }
         *     
         */
        public void setWanted(YesNoEnum value) {
            this.wanted = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="wanted" use="required" type="{}yesNoEnum" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class News {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected YesNoEnum wanted;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the wanted property.
         * 
         * @return
         *     possible object is
         *     {@link YesNoEnum }
         *     
         */
        public YesNoEnum getWanted() {
            return wanted;
        }

        /**
         * Sets the value of the wanted property.
         * 
         * @param value
         *     allowed object is
         *     {@link YesNoEnum }
         *     
         */
        public void setWanted(YesNoEnum value) {
            this.wanted = value;
        }

    }

}
