//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 12:57:52 AM MESZ 
//


package de.odenthma.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InformationenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformationenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Schwierigkeit" type="{http://www.w3schools.com}doubleValueEnum"/>
 *         &lt;element name="Terrain" type="{http://www.w3schools.com}doubleValueEnum"/>
 *         &lt;element name="Land" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Bundesland" type="{http://www.w3schools.com}bundeslandEnum"/>
 *         &lt;element name="Provinz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BeschreibungKlein" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BeschreibungGross" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hinweise" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GeschaetzteZeit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TravelBug" type="{http://www.w3schools.com}yesNoEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformationenType", propOrder = {
    "schwierigkeit",
    "terrain",
    "land",
    "bundesland",
    "provinz",
    "beschreibungKlein",
    "beschreibungGross",
    "hinweise",
    "geschaetzteZeit",
    "travelBug"
})
public class InformationenType {

    @XmlElement(name = "Schwierigkeit", namespace = "http://www.w3schools.com")
    protected double schwierigkeit;
    @XmlElement(name = "Terrain", namespace = "http://www.w3schools.com")
    protected double terrain;
    @XmlElement(name = "Land", namespace = "http://www.w3schools.com", required = true)
    protected String land;
    @XmlElement(name = "Bundesland", namespace = "http://www.w3schools.com", required = true)
    protected BundeslandEnum bundesland;
    @XmlElement(name = "Provinz", namespace = "http://www.w3schools.com", required = true)
    protected String provinz;
    @XmlElement(name = "BeschreibungKlein", namespace = "http://www.w3schools.com", required = true)
    protected String beschreibungKlein;
    @XmlElement(name = "BeschreibungGross", namespace = "http://www.w3schools.com", required = true)
    protected String beschreibungGross;
    @XmlElement(name = "Hinweise", namespace = "http://www.w3schools.com", required = true)
    protected String hinweise;
    @XmlElement(name = "GeschaetzteZeit", namespace = "http://www.w3schools.com", required = true)
    protected BigDecimal geschaetzteZeit;
    @XmlElement(name = "TravelBug", namespace = "http://www.w3schools.com", required = true)
    protected YesNoEnum travelBug;

    /**
     * Gets the value of the schwierigkeit property.
     * 
     */
    public double getSchwierigkeit() {
        return schwierigkeit;
    }

    /**
     * Sets the value of the schwierigkeit property.
     * 
     */
    public void setSchwierigkeit(double value) {
        this.schwierigkeit = value;
    }

    /**
     * Gets the value of the terrain property.
     * 
     */
    public double getTerrain() {
        return terrain;
    }

    /**
     * Sets the value of the terrain property.
     * 
     */
    public void setTerrain(double value) {
        this.terrain = value;
    }

    /**
     * Gets the value of the land property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLand() {
        return land;
    }

    /**
     * Sets the value of the land property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLand(String value) {
        this.land = value;
    }

    /**
     * Gets the value of the bundesland property.
     * 
     * @return
     *     possible object is
     *     {@link BundeslandEnum }
     *     
     */
    public BundeslandEnum getBundesland() {
        return bundesland;
    }

    /**
     * Sets the value of the bundesland property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundeslandEnum }
     *     
     */
    public void setBundesland(BundeslandEnum value) {
        this.bundesland = value;
    }

    /**
     * Gets the value of the provinz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinz() {
        return provinz;
    }

    /**
     * Sets the value of the provinz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinz(String value) {
        this.provinz = value;
    }

    /**
     * Gets the value of the beschreibungKlein property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeschreibungKlein() {
        return beschreibungKlein;
    }

    /**
     * Sets the value of the beschreibungKlein property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeschreibungKlein(String value) {
        this.beschreibungKlein = value;
    }

    /**
     * Gets the value of the beschreibungGross property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeschreibungGross() {
        return beschreibungGross;
    }

    /**
     * Sets the value of the beschreibungGross property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeschreibungGross(String value) {
        this.beschreibungGross = value;
    }

    /**
     * Gets the value of the hinweise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHinweise() {
        return hinweise;
    }

    /**
     * Sets the value of the hinweise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHinweise(String value) {
        this.hinweise = value;
    }

    /**
     * Gets the value of the geschaetzteZeit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGeschaetzteZeit() {
        return geschaetzteZeit;
    }

    /**
     * Sets the value of the geschaetzteZeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGeschaetzteZeit(BigDecimal value) {
        this.geschaetzteZeit = value;
    }

    /**
     * Gets the value of the travelBug property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoEnum }
     *     
     */
    public YesNoEnum getTravelBug() {
        return travelBug;
    }

    /**
     * Sets the value of the travelBug property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoEnum }
     *     
     */
    public void setTravelBug(YesNoEnum value) {
        this.travelBug = value;
    }

}
