//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.04 at 12:57:52 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3schools.com")
package de.odenthma.jaxb;
